apiVersion: v1
kind: Namespace
metadata:
  name: kt

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kt-npd-server
  namespace: kt
  labels:
    app: kt-npd-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kt-npd-server
  template:
    metadata:
      labels:
        app: kt-npd-server
    spec:
      containers:
      - name: kt-npd-server
        image: todohub/kt-npd-server:v0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: kt-npd-server
  namespace: kt
  labels:
    app: kt-npd-server
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: kt-npd-server
  type: ClusterIP