apiVersion: v1
kind: Namespace
metadata:
  name: kt

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-server
  namespace: kt
  labels:
    app: ns-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ns-server
  template:
    metadata:
      labels:
        app: ns-server
    spec:
      containers:
      - name: ns-server
        image: todohub/ns-server:v0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ns-server
  namespace: kt
  labels:
    app: ns-server
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: ns-server
  type: ClusterIP